export const DEFAULT_THEME_CONFIG = {
  global: {},
  local: {}
};

export const DYNAMIC_THEME_USER_CONFIG = 'DYNAMIC_THEME_USER_CONFIG';

export const DYNAMIC_THEME_PREVIEW_CONFIG = 'DYNAMIC_THEME_PREVIEW_CONFIG';

export const ACTION_DOWNLOAD_THEME = 'DYNAMIC_THEME_ACTION_DOWNLOAD';

export const ACTION_APPLY_THEME = 'DYNAMIC_THEME_ACTION_ALLPY_CSS';

export const ACTION_COMPONECT_SELECT = 'DYNAMIC_THEME_ACTION_COMPONECT_SELECT';

export const ACTION_USER_CONFIG_UPDATE = 'DYNAMIC_THEME_USER_CONFIG_UPDATE';
