/* Automatically generated by './build/bin/build-component.js' */

import Pagination from 'packages/pagination/index.js';
import Dialog from 'packages/dialog/index.js';
import Autocomplete from 'packages/autocomplete/index.js';
import Dropdown from 'packages/dropdown/index.js';
import DropdownMenu from 'packages/dropdown-menu/index.js';
import DropdownItem from 'packages/dropdown-item/index.js';
import Menu from 'packages/menu/index.js';
import Submenu from 'packages/submenu/index.js';
import MenuItem from 'packages/menu-item/index.js';
import MenuItemGroup from 'packages/menu-item-group/index.js';
import Input from 'packages/input/index.js';
import InputNumber from 'packages/input-number/index.js';
import Radio from 'packages/radio/index.js';
import RadioGroup from 'packages/radio-group/index.js';
import RadioButton from 'packages/radio-button/index.js';
import Checkbox from 'packages/checkbox/index.js';
import CheckboxButton from 'packages/checkbox-button/index.js';
import CheckboxGroup from 'packages/checkbox-group/index.js';
import Switch from 'packages/switch/index.js';
import Select from 'packages/select/index.js';
import Option from 'packages/option/index.js';
import OptionGroup from 'packages/option-group/index.js';
import Button from 'packages/button/index.js';
import ButtonGroup from 'packages/button-group/index.js';
import Table from 'packages/table/index.js';
import TableColumn from 'packages/table-column/index.js';
import DatePicker from 'packages/date-picker/index.js';
import TimeSelect from 'packages/time-select/index.js';
import TimePicker from 'packages/time-picker/index.js';
import Popover from 'packages/popover/index.js';
import Tooltip from 'packages/tooltip/index.js';
import Breadcrumb from 'packages/breadcrumb/index.js';
import BreadcrumbItem from 'packages/breadcrumb-item/index.js';
import Form from 'packages/form/index.js';
import FormItem from 'packages/form-item/index.js';
import Tabs from 'packages/tabs/index.js';
import TabPane from 'packages/tab-pane/index.js';
import Tag from 'packages/tag/index.js';
import Tree from 'packages/tree/index.js';
import Alert from 'packages/alert/index.js';
import Slider from 'packages/slider/index.js';
import Icon from 'packages/icon/index.js';
import Row from 'packages/row/index.js';
import Col from 'packages/col/index.js';
import Upload from 'packages/upload/index.js';
import Progress from 'packages/progress/index.js';
import Spinner from 'packages/spinner/index.js';
import Badge from 'packages/badge/index.js';
import Card from 'packages/card/index.js';
import Rate from 'packages/rate/index.js';
import Steps from 'packages/steps/index.js';
import Step from 'packages/step/index.js';
import Carousel from 'packages/carousel/index.js';
import Scrollbar from 'packages/scrollbar/index.js';
import CarouselItem from 'packages/carousel-item/index.js';
import Collapse from 'packages/collapse/index.js';
import CollapseItem from 'packages/collapse-item/index.js';
import Cascader from 'packages/cascader/index.js';
import ColorPicker from 'packages/color-picker/index.js';
import Transfer from 'packages/transfer/index.js';
import Container from 'packages/container/index.js';
import Header from 'packages/header/index.js';
import Aside from 'packages/aside/index.js';
import Main from 'packages/main/index.js';
import Footer from 'packages/footer/index.js';
import Timeline from 'packages/timeline/index.js';
import TimelineItem from 'packages/timeline-item/index.js';
import Link from 'packages/link/index.js';
import Divider from 'packages/divider/index.js';
import Image from 'packages/image/index.js';
import Calendar from 'packages/calendar/index.js';
import Backtop from 'packages/backtop/index.js';
import PageHeader from 'packages/page-header/index.js';
import CascaderPanel from 'packages/cascader-panel/index.js';
import Avatar from 'packages/avatar/index.js';
import Drawer from 'packages/drawer/index.js';
import Statistic from 'packages/statistic/index.js';
import Popconfirm from 'packages/popconfirm/index.js';
import Skeleton from 'packages/skeleton/index.js';
import SkeletonItem from 'packages/skeleton-item/index.js';
import Empty from 'packages/empty/index.js';
import Descriptions from 'packages/descriptions/index.js';
import DescriptionsItem from 'packages/descriptions-item/index.js';
import Result from 'packages/result/index.js';

var CONFIG_COMPONENTS = {
  Pagination: Pagination.name,
  Dialog: Dialog.name,
  Autocomplete: Autocomplete.name,
  Dropdown: Dropdown.name,
  DropdownMenu: DropdownMenu.name,
  DropdownItem: DropdownItem.name,
  Menu: Menu.name,
  Submenu: Submenu.name,
  MenuItem: MenuItem.name,
  MenuItemGroup: MenuItemGroup.name,
  Input: Input.name,
  InputNumber: InputNumber.name,
  Radio: Radio.name,
  RadioGroup: RadioGroup.name,
  RadioButton: RadioButton.name,
  Checkbox: Checkbox.name,
  CheckboxButton: CheckboxButton.name,
  CheckboxGroup: CheckboxGroup.name,
  Switch: Switch.name,
  Select: Select.name,
  Option: Option.name,
  OptionGroup: OptionGroup.name,
  Button: Button.name,
  ButtonGroup: ButtonGroup.name,
  Table: Table.name,
  TableColumn: TableColumn.name,
  DatePicker: DatePicker.name,
  TimeSelect: TimeSelect.name,
  TimePicker: TimePicker.name,
  Popover: Popover.name,
  Tooltip: Tooltip.name,
  Breadcrumb: Breadcrumb.name,
  BreadcrumbItem: BreadcrumbItem.name,
  Form: Form.name,
  FormItem: FormItem.name,
  Tabs: Tabs.name,
  TabPane: TabPane.name,
  Tag: Tag.name,
  Tree: Tree.name,
  Alert: Alert.name,
  Slider: Slider.name,
  Icon: Icon.name,
  Row: Row.name,
  Col: Col.name,
  Upload: Upload.name,
  Progress: Progress.name,
  Spinner: Spinner.name,
  Badge: Badge.name,
  Card: Card.name,
  Rate: Rate.name,
  Steps: Steps.name,
  Step: Step.name,
  Carousel: Carousel.name,
  Scrollbar: Scrollbar.name,
  CarouselItem: CarouselItem.name,
  Collapse: Collapse.name,
  CollapseItem: CollapseItem.name,
  Cascader: Cascader.name,
  ColorPicker: ColorPicker.name,
  Transfer: Transfer.name,
  Container: Container.name,
  Header: Header.name,
  Aside: Aside.name,
  Main: Main.name,
  Footer: Footer.name,
  Timeline: Timeline.name,
  TimelineItem: TimelineItem.name,
  Link: Link.name,
  Divider: Divider.name,
  Image: Image.name,
  Calendar: Calendar.name,
  Backtop: Backtop.name,
  PageHeader: PageHeader.name,
  CascaderPanel: CascaderPanel.name,
  Avatar: Avatar.name,
  Drawer: Drawer.name,
  Statistic: Statistic.name,
  Popconfirm: Popconfirm.name,
  Skeleton: Skeleton.name,
  SkeletonItem: SkeletonItem.name,
  Empty: Empty.name,
  Descriptions: Descriptions.name,
  DescriptionsItem: DescriptionsItem.name,
  Result: Result.name
};

var COMPONENT_PREFIX = 'Dy';

export function getComponentPrefix() {
  return COMPONENT_PREFIX;
};

export function injectComponent(injectComps) {
  injectComps.forEach(([name, component]) => {
    if (!name) {
      console.error('[Dynamic Error]注册表单项名称不能为空');
      return;
    }
    if (!component) {
      console.error('[Dynamic Error]注册表单项组件名称不能为空');
      return;
    }

    CONFIG_COMPONENTS[name] = component.name;
  });
};

export function getComponentByName(name) {
  if (!name) {
    console.error('[Dynamic Error]表单项不能为空');
    return;
  }
  // eslint-disable-next-line
  if (!CONFIG_COMPONENTS[name]) {
    console.error(`[Dynamic Error] 表单组件不支持的表单项：${name}`);
    return;
  }
  return CONFIG_COMPONENTS[name];
};

export function installComponent(Vue, component) {
  Vue.component(component.name, component);
}
