/* Automatically generated by './build/bin/build-component.js' */

import Pagination from 'packages/pagination/index.js';
import Dialog from 'packages/dialog/index.js';
import Autocomplete from 'packages/autocomplete/index.js';
import Dropdown from 'packages/dropdown/index.js';
import DropdownMenu from 'packages/dropdown-menu/index.js';
import DropdownItem from 'packages/dropdown-item/index.js';
import Menu from 'packages/menu/index.js';
import Submenu from 'packages/submenu/index.js';
import MenuItem from 'packages/menu-item/index.js';
import MenuItemGroup from 'packages/menu-item-group/index.js';
import Input from 'packages/input/index.js';
import InputNumber from 'packages/input-number/index.js';
import Radio from 'packages/radio/index.js';
import RadioGroup from 'packages/radio-group/index.js';
import RadioButton from 'packages/radio-button/index.js';
import Checkbox from 'packages/checkbox/index.js';
import CheckboxButton from 'packages/checkbox-button/index.js';
import CheckboxGroup from 'packages/checkbox-group/index.js';
import Switch from 'packages/switch/index.js';
import Select from 'packages/select/index.js';
import Option from 'packages/option/index.js';
import OptionGroup from 'packages/option-group/index.js';
import Button from 'packages/button/index.js';
import ButtonGroup from 'packages/button-group/index.js';
import Table from 'packages/table/index.js';
import TableColumn from 'packages/table-column/index.js';
import DatePicker from 'packages/date-picker/index.js';
import TimeSelect from 'packages/time-select/index.js';
import TimePicker from 'packages/time-picker/index.js';
import Popover from 'packages/popover/index.js';
import Tooltip from 'packages/tooltip/index.js';
import Breadcrumb from 'packages/breadcrumb/index.js';
import BreadcrumbItem from 'packages/breadcrumb-item/index.js';
import Form from 'packages/form/index.js';
import FormItem from 'packages/form-item/index.js';
import Tabs from 'packages/tabs/index.js';
import TabPane from 'packages/tab-pane/index.js';
import Tag from 'packages/tag/index.js';
import Tree from 'packages/tree/index.js';
import Alert from 'packages/alert/index.js';
import Slider from 'packages/slider/index.js';
import Icon from 'packages/icon/index.js';
import Row from 'packages/row/index.js';
import Col from 'packages/col/index.js';
import Upload from 'packages/upload/index.js';
import Progress from 'packages/progress/index.js';
import Spinner from 'packages/spinner/index.js';
import Badge from 'packages/badge/index.js';
import Card from 'packages/card/index.js';
import Rate from 'packages/rate/index.js';
import Steps from 'packages/steps/index.js';
import Step from 'packages/step/index.js';
import Carousel from 'packages/carousel/index.js';
import Scrollbar from 'packages/scrollbar/index.js';
import CarouselItem from 'packages/carousel-item/index.js';
import Collapse from 'packages/collapse/index.js';
import CollapseItem from 'packages/collapse-item/index.js';
import Cascader from 'packages/cascader/index.js';
import ColorPicker from 'packages/color-picker/index.js';
import Transfer from 'packages/transfer/index.js';
import Container from 'packages/container/index.js';
import Header from 'packages/header/index.js';
import Aside from 'packages/aside/index.js';
import Main from 'packages/main/index.js';
import Footer from 'packages/footer/index.js';
import Timeline from 'packages/timeline/index.js';
import TimelineItem from 'packages/timeline-item/index.js';
import Link from 'packages/link/index.js';
import Divider from 'packages/divider/index.js';
import Image from 'packages/image/index.js';
import Calendar from 'packages/calendar/index.js';
import Backtop from 'packages/backtop/index.js';
import PageHeader from 'packages/page-header/index.js';
import CascaderPanel from 'packages/cascader-panel/index.js';
import Avatar from 'packages/avatar/index.js';
import Drawer from 'packages/drawer/index.js';
import Statistic from 'packages/statistic/index.js';
import SvgIcon from 'packages/svg-icon/index.js';
import Popconfirm from 'packages/popconfirm/index.js';
import Skeleton from 'packages/skeleton/index.js';
import SkeletonItem from 'packages/skeleton-item/index.js';
import Empty from 'packages/empty/index.js';
import Descriptions from 'packages/descriptions/index.js';
import DescriptionsItem from 'packages/descriptions-item/index.js';
import Result from 'packages/result/index.js';
import DraggableResizable from 'packages/draggable-resizable/index.js';

var CONFIG_COMPONENTS = {
  Pagination: Pagination,
  Dialog: Dialog,
  Autocomplete: Autocomplete,
  Dropdown: Dropdown,
  DropdownMenu: DropdownMenu,
  DropdownItem: DropdownItem,
  Menu: Menu,
  Submenu: Submenu,
  MenuItem: MenuItem,
  MenuItemGroup: MenuItemGroup,
  Input: Input,
  InputNumber: InputNumber,
  Radio: Radio,
  RadioGroup: RadioGroup,
  RadioButton: RadioButton,
  Checkbox: Checkbox,
  CheckboxButton: CheckboxButton,
  CheckboxGroup: CheckboxGroup,
  Switch: Switch,
  Select: Select,
  Option: Option,
  OptionGroup: OptionGroup,
  Button: Button,
  ButtonGroup: ButtonGroup,
  Table: Table,
  TableColumn: TableColumn,
  DatePicker: DatePicker,
  TimeSelect: TimeSelect,
  TimePicker: TimePicker,
  Popover: Popover,
  Tooltip: Tooltip,
  Breadcrumb: Breadcrumb,
  BreadcrumbItem: BreadcrumbItem,
  Form: Form,
  FormItem: FormItem,
  Tabs: Tabs,
  TabPane: TabPane,
  Tag: Tag,
  Tree: Tree,
  Alert: Alert,
  Slider: Slider,
  Icon: Icon,
  Row: Row,
  Col: Col,
  Upload: Upload,
  Progress: Progress,
  Spinner: Spinner,
  Badge: Badge,
  Card: Card,
  Rate: Rate,
  Steps: Steps,
  Step: Step,
  Carousel: Carousel,
  Scrollbar: Scrollbar,
  CarouselItem: CarouselItem,
  Collapse: Collapse,
  CollapseItem: CollapseItem,
  Cascader: Cascader,
  ColorPicker: ColorPicker,
  Transfer: Transfer,
  Container: Container,
  Header: Header,
  Aside: Aside,
  Main: Main,
  Footer: Footer,
  Timeline: Timeline,
  TimelineItem: TimelineItem,
  Link: Link,
  Divider: Divider,
  Image: Image,
  Calendar: Calendar,
  Backtop: Backtop,
  PageHeader: PageHeader,
  CascaderPanel: CascaderPanel,
  Avatar: Avatar,
  Drawer: Drawer,
  Statistic: Statistic,
  SvgIcon: SvgIcon,
  Popconfirm: Popconfirm,
  Skeleton: Skeleton,
  SkeletonItem: SkeletonItem,
  Empty: Empty,
  Descriptions: Descriptions,
  DescriptionsItem: DescriptionsItem,
  Result: Result,
  DraggableResizable: DraggableResizable
};

var COMPONENT_PREFIX = 'Dy';

export function getComponentPrefix() {
  return COMPONENT_PREFIX;
};

export function injectComponent(injectComps) {
  injectComps.forEach(([name, component]) => {
    if (!name) {
      console.error('[Dynamic Error]注册表单项名称不能为空');
      return;
    }
    if (!component) {
      console.error('[Dynamic Error]注册表单项组件名称不能为空');
      return;
    }

    CONFIG_COMPONENTS[name] = component;
  });
};

export function getComponentByName(name) {
  if (!name) {
    console.error('[Dynamic Error]表单项不能为空');
    return;
  }
  // eslint-disable-next-line
  if (!CONFIG_COMPONENTS[name]) {
    console.error(`[Dynamic Error] 表单组件不支持的表单项：${name}`);
    return;
  }
  return CONFIG_COMPONENTS[name];
};

export function installComponent(Vue, component) {
  Vue.component(component.name, component);
}
